# Generated by Django 4.2.7 on 2023-11-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_entregable_estudiante_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='mombre',
            new_name='nombre',
        ),
    ]
